### ISSUE TITLE
Selection box

### ISSUE THREAD

**Issue by wasade** [biocore/emperor#625] opened 2017-11-24 18:06 UTC
I'm not sure if this is a duplicate but I can't find it. I know it's come up through the years. It would be really useful to be able to draw a box around a set of points, and trigger a subsequent action. An immediately useful example would be to select a set of samples and as the action have those sample IDs get automatically copied into the copybuffer (@ekopylova's idea). Support for drawing a selection box over a set of samples, and triggering an action like the copybuffer, setups the ability to trigger more complex operations such as regenerating PCoA on just the subset of points in the box.

**Comment by ElDeveloper** [comment] 2017-11-27 19:15
This is a duplicate of https://github.com/biocore/emperor/issues/153. After looking at this issue I came across this [JSBin](http://jsbin.com/tamoce/3/edit?js,output) (linked in [this THREE.js issue](https://github.com/mrdoob/three.js/issues/1826)). I believe we might be able to use that or some of the other solutions linked by the author.

**Closed by ElDeveloper** 2017-11-27 19:15 UTC
