### ISSUE TITLE
Emperor export format in qiita

### ISSUE THREAD

**Issue by josias2** [biocore/emperor#791] opened 2020-10-22 16:25 UTC
I have just finished an analysis using qiita and I am wondering why an option to save the plot in the *.svg format is no longer available.  *.svg is available only for the plot legend

**Comment by ElDeveloper** [comment] 2020-10-26 17:37
Hi @josias2, how many samples do you have in your analysis? I wonder if you are not seeing this option because you have more than 20,000 samples.

**Comment by josias2** [comment] 2020-10-26 18:09
No. We have 29 samples.
Em seg, 26 de out de 2020 14:37, Yoshiki Vázquez Baeza <
notifications@github.com> escreveu:

**Comment by ElDeveloper** [comment] 2020-10-30 00:54
I was able to reproduce this problem in Safari but not in Chrome, would you be able to try a different browser?

**Comment by josias2** [comment] 2020-10-30 07:54
I will try. Thanks so much.

Em qui., 29 de out. de 2020 às 21:55, Yoshiki Vázquez Baeza <
notifications@github.com> escreveu:

**Comment by ElDeveloper** [comment] 2021-08-06 16:50
@josias2, I'm closing this issue but feel free to re-open if you weren't able to solve your problem.

**Closed by ElDeveloper** 2021-08-06 16:50 UTC

**Comment by josias2** [comment] 2021-08-06 17:45
It is ok with this issue. I noticed that it is not possible to save in the
*.svg format. Therefore it may be closed.
Thank you

Em sex., 6 de ago. de 2021 às 13:50, Yoshiki Vázquez Baeza <
***@***.***> escreveu:
