### ISSUE TITLE
Metadata types

### ISSUE THREAD

**Issue by mortonjt** [biocore/emperor#429] opened 2015-12-04 19:57 UTC
It may be worthwhile to have Emperor aware of different data types( i.e. continuous variables and categorical variables).  

That way, it may be easier to visualize gradients vs categories.

**Comment by cuttlefishh** [comment] 2015-12-04 20:02
Agree this would be useful. Pandas integration sounds like a good way to go as it recognizes data types automatically (floats, ints, strings).

**Comment by ElDeveloper** [comment] 2015-12-04 20:23
What would this data-type detection would look like, i.e. what effects
would you expect to see on the plot?

**Comment by cuttlefishh** [comment] 2015-12-04 20:43
I think for strings and ints the current behavior is best, where each category/value gets a color. If all numerical values are ints, there probably aren't going to be too many different ones. 

However if one or more of the values are floats, that should be a float column and should be treated as a continuous variable. For the plot, something like what `ili does would be good: a scale bar showing min and max, with several color maps to choose from. With `ili you can also change the scale from linear to log, and set the min/max automatically or manually. Emulating the functionality of `ili would be a fantastic outcome.

**Comment by josenavas** [comment] 2015-12-04 21:12
I disagree on using pandas for recognizing data types - it has been a pain in Qiita.
In my opinion, this could be as simple as having a checkbox in the interface `continuous` that then it grabs the values, sorts them and applies the scale bar.

The reason why I don't think type inference is good is because not all the numerical values should be shown as a continuous variable, so letting the user choose through the interface is the easy way to go.

**Comment by cuttlefishh** [comment] 2015-12-04 21:13
That sounds reasonable. I agree.

**Comment by antgonza** [comment] 2015-12-04 21:46
That's the way we used to have it, one checkbox to color by gradient or by categorical colors. This was OK cause we only had one color scheme for each. Now, we have different for both continuous and categorical. Should we have a checkbox that only shows categorical or continuous colors? What will be the most desirable?

**Comment by cuttlefishh** [comment] 2015-12-04 22:00
My preference would be for categorical colors to stay the same. Then have a checkbox for continuous. When you check this, a set of additional options appears like those of the ili toolbox. One of these is colormap, which is a set of color brewer gradients (sequential and diverging).

**Comment by ElDeveloper** [comment] 2015-12-07 17:11
Thanks guys, I think this is a bit of a duplicate of #311, and somewhat related to #336.

I'll add the note about scaling the data, asides from that everything else, should already be supported.

**Closed by ElDeveloper** 2015-12-07 17:11 UTC
Labels: group discussion, question
