### ISSUE TITLE
Emperor freezes with >4500 samples

### ISSUE THREAD

**Issue by bctaylor** [biocore/emperor#403] opened 2015-05-29 16:53 UTC
Can't really do anything on emperor with this large of a dataset. Please help! 
Thanks so much.

**Comment by ElDeveloper** [comment] 2015-05-29 17:02
I doubt it's the number of samples, it is likely the number of unique
values in your metadata i.e. it should load fine if you start off with a
metadata category that has ~500 unique metadata values, when this
number starts getting larger, that's when we start seeing problems. Does
the plot fail to load?

**Comment by antgonza** [comment] 2015-05-29 17:07
Agree with @ElDeveloper that the issue is number of metadata columns and number of unique values within this data. Note that we are looking into ways to make this better in future releases but at this point the best is to trim down you mapping file by removing those columns.

**Comment by JWDebelius** [comment] 2015-05-29 17:42
I have an issue with the American Gut fecal dataset as well, at 2000 samples. I can't re-color, even when I limit to a single, continuous variable.

**Comment by ElDeveloper** [comment] 2015-05-29 17:47
@JWDebelius, if you have time, please let me know, I would like to have
a look at the problem by myself.

**Comment by ElDeveloper** [comment] 2015-06-01 19:19
Everyone, I troubleshooted this with @JWDebelius on Friday and the reason why emperor was freezing is because the number of unique values in the category she wanted to view was about 2300. When I did a small experiment, the renderer was able to change the color of all the samples in less than a second, but the DOM would not update and ultimately crash the tab.

My suggestion for @JWDebelius was to reduce the precision of the continuous values she has in her mapping file, from 8 -> 2, which should probably do the trick and although not perfect, will be most likely not perceptible by the eye.

@bctaylor, can you let us know if a similar solution won't work with your problem and reopen as needed?

I'm closing this issue for now. The problem in question is a duplicate of #178, which will be addressed by #401 and the re-architecture of the JS backend.

**Closed by ElDeveloper** 2015-06-01 19:19 UTC
Labels: group discussion, performance, question
